CONN_SUCCESS = 'connection_successful'
NEW_GAME = 'new_game'
JOIN_GAME = 'join_game'
JOIN_GAME_ERROR = 'invalid_game_or_pwd'
GAME_JOINED = 'game_joined'
PLAYERS_CHANGED = 'players_changed'
ASSIGN_ROLES = 'assign_roles'
ROLES_ASSIGNED = 'roles_assigned'
